[tool.poetry]
name = "chuninewbot"
version = "0.1.0"
description = ""
authors = ["beerpiss <lacvtg.a1.2023@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.1.0"
aiohttp = "^3.8.5"
yarl = "^1.8.2"
beautifulsoup4 = "^4.11.2"
python-dotenv = "^1.0.0"
dataclasses-json = "^0.5.7"
aiolimiter = "^1.0.0"
lxml = "^4.9.2"
pillow = "^9.5.0"
jarowinkler = "^1.2.3"
alembic = "^1.11.2"
sqlalchemy = {version = "^2.0.19", extras = ["asyncio"]}
tzdata = "^2023.3"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
types-beautifulsoup4 = "^4.12.0.1"
jishaku = "^2.5.1"
pre-commit = "^3.3.3"
ruff = "^0.0.284"

[tool.isort]
profile = "black"

[tool.ruff]
select = ["ASYNC", "B", "BLE", "C4", "DTZ", "E", "EM", "F", "FBT", "FLY", "ISC", "Q", "PERF", "PGH", "PIE", "PTH", "RET", "RSE", "RUF", "SIM", "TCH", "TRY", "TID252", "W"]
ignore = ["E501"]
unfixable = ["B"]

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401"]
"bot.py" = ["E402"]
"chunithm_net/consts.py" = ["RUF001"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
