name: Test DB generation

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
    paths:
      - ".github/workflows/test_creating_db.yaml"
      - "utils/config.py"  # Contains default value for DB path
      - "database/**"
      - "dbutils.py"
      - "poetry.lock"
      - "pyproject.toml"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: poetry

      - name: Install dependencies
        run: poetry install --without dev --all-extras

      - name: Configuration
        run: |
           cp bot.example.ini bot.ini
           sed -i 's/# chunirec_token = <token>/chunirec_token = ${{ secrets.CHUNIREC_TOKEN }}/' bot.ini

      - name: Create database from schema
        run: poetry run python dbutils.py create

      - name: Update database with information from Chunirec + Zetaraku + Official website
        run: poetry run python dbutils.py update chunirec

      - name: Update sdvx.in chart views
        run: poetry run python dbutils.py update sdvxin

      - name: Update database aliases
        run: poetry run python dbutils.py update alias

      - name: Upload created database
        uses: actions/upload-artifact@v3
        with:
          name: database
          path: database/database.sqlite3
